name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage
